baseURL = "https://danyspin97.github.io/"
languageCode = "en-us"
title = "DanySpin97's site"
theme = "hugo-goa"
enableRobotsTXT = true

[params]
author = "Danilo Spinella"
intro = "Aspirant developer"
description = "Engineering student. Linux enthusiast.<br/>Exherbo user. Terminal lover.<br/>Avid music listener."
authorimage = "profile.jpg"
dateformat = "Monday, Jan 2, 2006"

[[menu.main]]
    name= "blog"
    identifier = "blog"
    weight = 300
    url = "/blog/"
[[menu.main]]
    name = "projects"
    weight = 300
    url = "/projects/"

[params.social]
github = "DanySpin97"
linkedin = "DanySpin97"
email = "danyspin97@protonmail.com"

[params.meta]
description = "Personal site with portfolio and blog"
keywords = "minimalist,goa,hugo,developer,linux,exherbo,terminal"

[params.extra]
copyright = "© 2018 Danilo Spinella. [CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/)."
rss = true
highlightjs = true
