baseURL = "https://danyspin97.org/"
languageCode = "en-us"
title = "danyspin97's site"
author = "Danilo Spinella"
theme = "cocoa-eh"
enableRobotsTXT = true
builddrafts = true
canonifyurls = true

[permalinks]
blog  = "blog/:slug/"

[params]
#selfintro = "Engineering student"
description = "Engineering student. OpenSource contributor. Linux enthusiast. Exherbo user. Terminal lover. Avid music listener."
github = "danyspin97"
linkedin = "danyspin97"
email = "danyspin97@protonmail.com"
# avatar = "profile.jpg"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
include_rss = true
latestpostscount = 3
i18n_flags = true
cachebuster = true
noshowreadtime = false
mastodon = "//fosstodon.org/@danyspin97"
highlightjs = true
progressively = false
posts_navigation = true

[[menu.main]]
    name= "blog"
    identifier = "blog"
    weight = 300
    url = "/blog/"
[[menu.main]]
    name = "projects"
    weight = 300
    url = "/projects/"
