baseURL = "https://danyspin97.org/"
languageCode = "en-us"
title = "danyspin97's site"
author = "Danilo Spinella"
theme = "cocoa-eh"
enableRobotsTXT = true
builddrafts = false
canonifyurls = true

[permalinks]
blog  = "blog/:slug/"

[params]
description = "A passionate engineering student who writes about Unix related topics and tech stuff."
github = "danyspin97"
email = "me@danyspin97.org"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
include_rss = true
latestpostcount = 4
i18n_flags = true
cachebuster = true
noshowreadtime = false
#mastodon = "//pleroma.liveunix.org/@danyspin97"
highlightjs = true
progressively = false
posts_navigation = true
copyright = "CC BY-SA 4.0 © {year} Danilo Spinella"
copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
extracssfiles = ["css/image.css", "css/bigger-header.css"]

[[menu.main]]
    name= "blog"
    identifier = "blog"
    weight = 100
    url = "/blog/"
[[menu.main]]
    name = "projects"
    weight = 200
    url = "/projects/"
[[menu.main]]
    name = "talks"
    weight = 300
    url = "/talks/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4

