baseURL = "https://danyspin97.github.io/"
languageCode = "en-us"
title = "DanySpin97's site"
theme = "cocoa"
enableRobotsTXT = true

[permalinks]
blog  = "blog/:slug/"

[params]
author = "Danilo Spinella"
selfintro = "OpenSource contributor"
description = "Engineering student. Linux enthusiast. Exherbo user. Terminal lover. Avid music listener."
github = "//github.com/DanySpin97"
linkedin = "//linkedin.com/DanySpin97"
email = "danyspin97@protonmail.com"
# avatar = "profile.jpg"
dateformat = "Monday, Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
include_rss = true
latestpostscount = 3
i18n_flags = true
cachebuster = true
noshowreadtime = false
mastodon = "//fosstodon.org/@danyspin97"
highlightjs = true

[[menu.main]]
    name= "blog"
    identifier = "blog"
    weight = 300
    url = "/blog/"
[[menu.main]]
    name = "projects"
    weight = 300
    url = "/projects/"

